### ISSUE TITLE
[Minimal Errors] in ambientadditions-1.18.2-0.8.0.jar

### ISSUE THREAD

**Issue by DaDiGui** [VakyAndCodaIncorporated/AmbientAdditions#10]
- When looking at the RingTailed_Lemur entity. When I look at it with WYALA I get the following name: *entity.monkemadness.lemur*.
- *Golden Elephant Snail* its called Rabbit Snail
- Flying_fish appears in the entities but no egg exists

**Comment by Coda1552** [comment]
Flying fish was WIP and will be removed, and the ‘golden elephant snail’ will be renamed to Rabbit Snail in our next breaking update. The lemur isn’t even from our mod…
