### ISSUE TITLE
ambientadditions-1.19.2-0.1.2 Server not working

### ISSUE THREAD

**Issue by CreativeManul** [VakyAndCodaIncorporated/AmbientAdditions#11]
I run the bat file - the server does not turn on. I remove the mod - everything works.

**Comment by Coda1552** [comment]
Gonna need the log or crash report.

**Comment by CreativeManul** [comment]
[https://drive.google.com/file/d/1RCvvvn5C00sOG-fOpYt-hUzIn4HXPZCs/view?usp=share_link] So okay?

**Comment by Coda1552** [comment]
Thanks. Fixed in 0.1.3.

**Comment by CreativeManul** [comment]
<3 You are stunning!
