### ISSUE TITLE
1.20 port

### ISSUE THREAD

**Issue by smifflepuss** [VakyAndCodaIncorporated/AmbientAdditions#15]
Sorry to interrupt, but a 1.20 port would sound good for this mod.

**Comment by Coda1552** [comment]
You have balls, Gohken.

**Comment by smifflepuss** [comment]
> You have balls, Gohken.

Look, I've tried being nice to you on apologizing, but if you want to be rude, then I'll fucking be rude back to you.
Fuck you for acting like a retard and betraying me, Coda!

**Comment by smifflepuss** [comment]
Goodbye forever, Coda1552!

**Comment by VakyPanda** [comment]
TRAGIC???? TRAGIC

**Comment by TheAnnoyingOrca** [comment]
Never to recover

**Comment by Coda1552** [comment]
We did it....it's finally..........over.......................good lord that took too long

**Comment by ShrimplyGraus** [comment]
It’s so over! Goodbye forever!

**Comment by smifflepuss** [comment]
> We did it....it's finally..........over.......................good lord that took too long

You are literally stupid!

**Comment by Sindavar** [comment]
> > We did it....it's finally..........over.......................good lord that took too long
> 
> You are literally stupid!

This is not the definition of goodbye forever!!

**Comment by smifflepuss** [comment]
I know that

**Comment by gohkenytp** [comment]
Goodbye forever, Coda1552! (Once again, 😠)
