### ISSUE TITLE
Golden Snail overspawning

### ISSUE THREAD

**Issue by Maalakita** [VakyAndCodaIncorporated/AmbientAdditions#3]
Golden elephant snails spawn in every river, even preventing other mods' mobs to spawn on them.

**Comment by Shoes4Clues** [comment]
Can confirm this still happens as of the latest 1.18.2 release.

**Comment by Coda1552** [comment]
aaaaa

**Comment by Coda1552** [comment]
theres other bugs i missed. will lower their spawns more to see if that helps

**Comment by Coda1552** [comment]
Theres a config for spawning now in 1.18.2.
