### ISSUE TITLE
Server Crash from Yeti Crab and Snail

### ISSUE THREAD

**Issue by Spazmunki13** [VakyAndCodaIncorporated/AmbientAdditions#6]
Hello, my server has crashed twice and my reports seem to be mentioning some critters from your mod. Thought it might be useful for you.

[crash-2022-03-15_05.57.37-server.txt](https://github.com/VakyAndCodaIncorporated/AmbientAdditions/files/8282035/crash-2022-03-15_05.57.37-server.txt)
[crash-2022-03-17_02.39.27-server.txt](https://github.com/VakyAndCodaIncorporated/AmbientAdditions/files/8282036/crash-2022-03-17_02.39.27-server.txt)

**Comment by Coda1552** [comment]
The spawn config should fix this.
