### ISSUE TITLE
Game crashing on initilization

### ISSUE THREAD

**Issue by Lozf** [VakyAndCodaIncorporated/AmbientAdditions#9]
Game crashes on startup - It was working fine, but now won't load.

Forge 40.1.51
1.18.2 0.8.0

[crash-2022-06-24_02.26.47-fml.txt](https://github.com/VakyAndCodaIncorporated/AmbientAdditions/files/8975031/crash-2022-06-24_02.26.47-fml.txt)

[latest.log](https://github.com/VakyAndCodaIncorporated/AmbientAdditions/files/8975032/latest.log)

**Comment by Coda1552** [comment]
A friend was having a similar problem, not entirely sure whats going on. They said it works sometimes and crashes other times. Can I get any more info? Does it sometimes work? Have you tried with just ambient additions & geckolib?

**Comment by Lozf** [comment]
So restarting my computer took care of the crashing issue.  I don't think I tried it with just ambient additions and geckolib, but I was able to get everything to load after a restart, if that helps.

**Comment by Coda1552** [comment]
Oh, okay. I'll close this issue for now, then. If it comes back up, feel free to reopen.

**Comment by Lozf** [comment]
Ok, will do!
